name: EAS Production Build (Android & IOS) (EAS)

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  Build:
    name: EAS Production Build (Android & IOS) (EAS)
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + Yarn + install deps
        uses: ./.github/actions/setup-node-yarn-install
      - name: ⏱️ EAS Build
        run: echo "Here we would run the EAS Build command. TODO."
      # - name: ⏱️ EAS Build
      #   uses: ./.github/actions/eas-build
      #   with:
      #     APP_ENV: production
