name: Code Review GPT

on:
  pull_request:
    branches: [main]

jobs:
  run_code_review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove yarn.lock
        run: rm -f yarn.lock

      - name: Code Review GPT
        uses: mattzcarey/shippie@v0.20.0
        with:
          GITHUB_TOKEN: ${{ github.token }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL_STRING: 'openai:gpt-4.1-mini'
          REVIEW_LANGUAGE: 'English'
